version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5052:5052
    restart: always
    volumes:
      - ./static:/app/static
      - ./db:/app/db
volumes:
  static:
  db: